<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DTLS/DTLS.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <NativeConfiguration Condition="'$(Configuration)' == 'Debug'">debug</NativeConfiguration>
    <NativeConfiguration Condition="'$(NativeConfiguration)' == ''">release</NativeConfiguration>
    <NativeLibDir>$(MSBuildThisFileDirectory)../../native/target/$(NativeConfiguration)/</NativeLibDir>
    <NativeCargoReleaseArgument Condition="'$(NativeConfiguration)' != 'debug'">--release</NativeCargoReleaseArgument>
  </PropertyGroup>

  <Target Name="BuildNativeLib" BeforeTargets="CopyNativeLib">
    <Exec Command="cargo rustc $(NativeCargoReleaseArgument) --crate-type cdylib" WorkingDirectory="$(MSBuildThisFileDirectory)../../native" />
  </Target>

  <Target Name="CopyNativeLib" AfterTargets="Build">
    <ItemGroup>
      <NativeLib Include="$(NativeLibDir)dtls_native.dll" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
      <NativeLib Include="$(NativeLibDir)libdtls_native.so" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
      <NativeLib Include="$(NativeLibDir)libdtls_native.dylib" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
    </ItemGroup>
    <Copy SourceFiles="@(NativeLib)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
