<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>DTLS</PackageId>
    <Description>High-performance DTLS for .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>dtls</PackageTags>
    <Copyright>Copyright @ HMBSbige</Copyright>
    <PackageProjectUrl>https://github.com/HMBSbige/DTLS</PackageProjectUrl>
    <RepositoryUrl>https://github.com/HMBSbige/DTLS</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <DTLSNativeAssetsPath Condition="'$(DTLSNativeAssetsPath)' == ''">$(MSBuildThisFileDirectory)../../artifacts/native</DTLSNativeAssetsPath>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DTLS.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(DTLSNativeAssetsPath)/**/*" Pack="true" PackagePath="runtimes" />
    <None Update="buildTransitive/**/*" Pack="true" PackagePath="%(Identity)" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
